### ISSUE TITLE
Compatibility with SkyblockAddons

### ISSUE THREAD

**Issue by PyICoder** [asbyth/Tweaker2#1]
Your mod doesn't work when I use SkyblockAddons https://github.com/biscuut/SkyblockAddons.
I asked the developer and he said that the problem is the compatibility issue you can fix.

I'll put my log in here as well
[latest.log](https://github.com/asbyth/Tweaker2/files/3557653/latest.log)

**Comment by asbyth** [comment]
I'm currently in the process of rewriting it, the link to the new repository is [here](https://github.com/asbyth/Patcher). I'll let him know when it's done so he can redirect people to Patcher.
